### ISSUE TITLE
Error after install gem

### ISSUE THREAD

**Issue by Barlog951** [goco-inc/graphql-activerecord#22]
Hi

I have problem in my simple app
I just add gem 'graphql-activerecord' in Gemfile, install gems and I have this error

`<module:Models>': uninitialized constant GraphQL::Batch (NameError)`

**Comment by nostophilia** [comment]
`gem "graphql-batch"` and `bundle install`

**Comment by Barlog951** [comment]
I try this but same error :/

**Comment by theorygeek** [comment]
Any chance you could share the relevant lines from your Gemfile? Here's what I have in mine:

```ruby
gem 'graphql', '~> 1.4'
gem 'graphql-batch', '~> 0.3'
gem 'graphql-activerecord', '~> 0.9.1'
```
