### ISSUE TITLE
Apollo client and model_from_id

### ISSUE THREAD

**Issue by moimael** [goco-inc/graphql-activerecord#33]
Hi,

We are using graphql-activerecord for queries and it worked well for us. We are now trying to get mutations to work and got pretty close.

The only thing that is blocking us is the model_from_if callback. We are using Apollo client and client generated IDs.

Those IDs are uuid v4 but do not contain the model name like relay IDs does. Is there any other way we can get it in the model_from_id ? 

Thanks !

**Comment by theorygeek** [comment]
Sorry for the late reply! I'm guessing this is probably water under the bridge by now, but maybe this answer helps anyway.

First, let me make sure I'm understanding your situation. If you have a model like this:
```ruby
class ChildModel < ApplicationRecord
  belongs_to :parent_model
end
```

And then you define a mutation like this:
```ruby
mutator_definition = GraphQL::Models.define_mutator(self, ChildModel, null_behavior: :set_null) do
  attr :parent_model_id
end
```

The gem detects that [`parent_model_id` is a foreign key](https://github.com/goco-inc/graphql-activerecord/blob/master/lib/graphql/models/mutation_field_map.rb#L34), and when it creates the field, it uses GraphQL's ID type (ie, `types.ID`).

On the other side of things, when the gem receives input (when you call `apply_changes`), it will detect [if the input field is an ID field](https://github.com/goco-inc/graphql-activerecord/blob/master/lib/graphql/models/mutation_helpers/apply_changes.rb#L206), and if so, it will call your `model_from_id` proc to resolve the ID, and then get the model's _real_ ID.

The easiest way to override this behavior is to override the type of the field, which forces it to treat it like it's a dumb field:
```ruby
mutator_definition = GraphQL::Models.define_mutator(self, ChildModel, null_behavior: :set_null) do
  # Force it to be a string field
  attr :parent_model_id, type: types.String
end
```

That'll bypass the `model_from_id` logic entirely. The other thing you could do is a bit more hacky, but the reality is that the gem only tries to access the `id` field on your model. So you could do something like this:
```ruby
ModelShim = Struct.new(:id)
GraphQL::Models.model_from_id = -> (gid, ctx) { ModelShim.new(gid) }
```

The gem doesn't really need the whole model, it just needs the `id` on it; so this tricks it into working. A better long-term solution would be to provide more contextual info to that proc.
