### ISSUE TITLE
Error when declaring `GraphQL::Models.model_to_graphql_type`

### ISSUE THREAD

**Issue by nater540** [goco-inc/graphql-activerecord#39]
Following the instructions in the README file and declaring the `model_to_graphql_type` proc will generate an error:

```
/config/initializers/graphql_activerecord.rb:23:in `<top (required)>': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

I have it declared like so:
```
GraphQL::Models.model_to_graphql_type -> (model_class) { "Types::#{model_class.name}Type".safe_constantize }
```

Am I missing something extremely obvious? 😝

**Comment by nater540** [comment]
@theorygeek 
Sorry to pester, but any thoughts on this one by chance?

**Comment by vergenzt** [comment]
It looks like `GraphQL::Models.model_to_graphql_type` is [supposed to be configured via an accessor](https://github.com/goco-inc/graphql-activerecord/blob/a35773a91f9512e4ee2573404591831717549037/lib/graphql/activerecord.rb#L41), not a method call. (Though it looks like the docs make the same typo you did.)

Try this:
```rb
GraphQL::Models.model_to_graphql_type = -> (model_class) { "Types::#{model_class.name}Type".safe_constantize }
```

(i.e. with an equals sign).

**Comment by theorygeek** [comment]
@nater540 Hey, I apologize for my timing getting back to you. Were you able to try the solution that @vergenzt suggested? I think that should fix your issue.
